name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Exécuter les tests de l'Annuaire
      run: npx playwright test "Epic 2 - L'Annuaire" --reporter=line
    - name: Générer le rapport de test
      run: npx playwright show-report --output=report-annuaire
    - name: Archiver le rapport de l'Annuaire
      uses: actions/upload-artifact@v3
      if: ${{ !cancelled() }}
      with:
        name: rapport-tests-E2-annuaire
        path: playwright-report/report-E2-annuaire
        retention-days: 30
    - name: Exécuter les tests de la Zone sécurisée
      run: npx playwright test "Epic 3 - Zone sécurisée" --reporter=line
    - name: Générer le rapport de test
      run: npx playwright show-report --output=report-zone-securisee
    - name: Archiver le rapport de la Zone sécurisée
      uses: actions/upload-artifact@v3
      if: ${{ !cancelled() }}
      with:
        name: rapport-tests-E3-zone-securisee
        path: playwright-report/report-E3-zone-securisee
        retention-days: 30
    - name: Exécuter les tests de Contact
      run: npx playwright test "Epic 5 - Contact" --reporter=line
    - name: Générer le rapport de test
      run: npx playwright show-report --output=report-contact
    - name: Archiver le rapport de Contact
      uses: actions/upload-artifact@v3
      if: ${{ !cancelled() }}
      with:
        name: rapport-tests-E5-contact
        path: playwright-report/report-E5-contact
        retention-days: 30
